<?php 
$this->headTitle('PinCrowd - Social Bowling');
$this->headScript()->captureStart(); ?>
Ext.application({
    name: 'Pincrowd',
    launch: function() {
        Ext.create("Ext.TabPanel", {
            fullscreen: false,
            tabBarPosition: 'bottom',
            items: [
                {
                    title: 'Begin',
                    iconCls: 'favorites',
                    cls: 'home',
                    style: 'background:url(/images/bkg-splash.jpg) repeat;',
                    layout: {
                        type: 'vbox',
                        align: 'center'
                    },
                    html: [
                        '<div id="logo">',
                        '<img src="/images/pincrowd-logo.png" alt="PinCrowd - Social Bowling">',
                        '</div>'
                    ].join(""),
                    defaults: {
                        xtype: 'button',
                        margin: '10 10 0 10'
                    },
                    items: [
                        {
                            xtype: 'button',
                            text: 'Let\'s Bowl!',
                            ui: 'action',
                            docked: 'bottom',
                            align: 'center',
                            handler: function() {
                                p = Ext.ComponentQuery.query('[title="Begin"]')
                                p[0].parent.setActiveItem(1);
                            }
                        },
                        {
                            xtype: 'button',
                            text: 'Watch The Demo',
                            ui: 'action',
                            docked: 'bottom',
                            align: 'center',
                            handler: function() {
                                this.up('formpanel').submit();
                            }
                        }
                    ]
                },
                {
                    title: 'Bowlers',
                    iconCls: 'team',
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            html: 'Left Panel, 1/2 of total size',
                            items: [
                                {
                                    xtype: 'button',
                                    text: '1',
                                    handler: function() {
                                        p = Ext.ComponentQuery.query('[title="Bowlers"]')
                                        p[0].parent.setActiveItem(2);
                                    }
                                },
                                {
                                    xtype: 'button',
                                    text: '2',
                                    handler: function() {
                                        p = Ext.ComponentQuery.query('[title="Bowlers"]')
                                        p[0].parent.setActiveItem(2);
                                    }
                                },
                                {
                                    xtype: 'button',
                                    text: '3',
                                    handler: function() {
                                        p = Ext.ComponentQuery.query('[title="Bowlers"]')
                                        p[0].parent.setActiveItem(2);
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            html: 'Right Panel, 1/2 of total size',
                            items: [
                                {
                                    xtype: 'button',
                                    text: '4',
                                    handler: function() {
                                        p = Ext.ComponentQuery.query('[title="Bowlers"]')
                                        p[0].parent.setActiveItem(2);
                                    }
                                },
                                {
                                    xtype: 'button',
                                    text: '5',
                                    handler: function() {
                                        p = Ext.ComponentQuery.query('[title="Bowlers"]')
                                        p[0].parent.setActiveItem(2);
                                    }
                                },
                                {
                                    xtype: 'button',
                                    text: '6',
                                    handler: function() {
                                        p = Ext.ComponentQuery.query('[title="Bowlers"]')
                                        p[0].parent.setActiveItem(2);
                                    }
                                }
                            ]
                        }
                    ]
                },
                //this is the new item
                {
                    title: 'Games',
                    iconCls: 'more',
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            html: 'Left Panel, 1/2 of total size',
                            items: [
                                {
                                    xtype: 'button',
                                    text: '1',
                                    handler: function() {
                                        p = Ext.ComponentQuery.query('[title="Games"]')
                                        p[0].parent.setActiveItem(3);
                                    }
                                },
                                {
                                    xtype: 'button',
                                    text: '2',
                                    handler: function() {
                                        p = Ext.ComponentQuery.query('[title="Games"]')
                                        p[0].parent.setActiveItem(3);
                                    }
                                },
                                {
                                    xtype: 'button',
                                    text: '3',
                                    handler: function() {
                                        p = Ext.ComponentQuery.query('[title="Games"]')
                                        p[0].parent.setActiveItem(3);
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            html: 'Right Panel, 1/2 of total size',
                            items: [
                                {
                                    xtype: 'button',
                                    text: '4',
                                    handler: function() {
                                        p = Ext.ComponentQuery.query('[title="Games"]')
                                        p[0].parent.setActiveItem(3);
                                    }
                                },
                                {
                                    xtype: 'button',
                                    text: '5',
                                    handler: function() {
                                        p = Ext.ComponentQuery.query('[title="Games"]')
                                        p[0].parent.setActiveItem(3);
                                    }
                                },
                                {
                                    xtype: 'button',
                                    text: '6',
                                    handler: function() {
                                        p = Ext.ComponentQuery.query('[title="Games"]')
                                        p[0].parent.setActiveItem(3);
                                    }
                                }
                            ]
                        }
                    ]
                },
                //this is the new item
                {
                    title: 'Shoes',
                    iconCls: 'search',
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            html: 'Left Panel, 1/2 of total size',
                            items: [
                                {
                                    xtype: 'button',
                                    text: '1',
                                    handler: function() {
                                        p = Ext.ComponentQuery.query('[title="Shoes"]')
                                        p[0].parent.setActiveItem(4);
                                    }
                                },
                                {
                                    xtype: 'button',
                                    text: '2',
                                    handler: function() {
                                        p = Ext.ComponentQuery.query('[title="Shoes"]')
                                        p[0].parent.setActiveItem(4);
                                    }
                                },
                                {
                                    xtype: 'button',
                                    text: '3',
                                    handler: function() {
                                        p = Ext.ComponentQuery.query('[title="Shoes"]')
                                        p[0].parent.setActiveItem(4);
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            html: 'Right Panel, 1/2 of total size',
                            items: [
                                {
                                    xtype: 'button',
                                    text: '4',
                                    handler: function() {
                                        p = Ext.ComponentQuery.query('[title="Shoes"]')
                                        p[0].parent.setActiveItem(4);
                                    }
                                },
                                {
                                    xtype: 'button',
                                    text: '5',
                                    handler: function() {
                                        p = Ext.ComponentQuery.query('[title="Shoes"]')
                                        p[0].parent.setActiveItem(4);
                                    }
                                },
                                {
                                    xtype: 'button',
                                    text: '6',
                                    handler: function() {
                                        p = Ext.ComponentQuery.query('[title="Shoes"]')
                                        p[0].parent.setActiveItem(4);
                                    }
                                }
                            ]
                        }
                    ]
                },
                //this is the new item
                {
                    title: 'Payment',
                    iconCls: 'compose',
                    layout: 'vbox',
                    items: []
                }
            ]
        }).setActiveItem(0);
    }
});
<?php $this->headScript()->captureEnd();?>