<?php echo $this->headLink()->appendStylesheet($this->baseUrl('css/setup.css'));?>

<body id="logIn">
<div id="container">
    <header>
        <h1>Bowler #1</h1>
    </header>
    <section id="main">
        <div class="centering">
            <form action="<?php echo $this->baseUrl('auth'); ?>" method="post" name="logIn">
                <ul>
                    <li>
                        <input name="username" type="text" placeholder="First name" required>
                    </li>
<!--                     <li> -->
<!--                         <input name="lname" type="text" placeholder="Last name" required> -->
<!--                     </li> -->
                    <li>
                        <input name="password" type="password" placeholder="Password" required>
                    </li>
<!--                     <li> -->
<!--                         <input name="pass2" type="password" placeholder="Confirm password" required> -->
<!--                     </li> -->
                </ul>
                <a href="<?php echo $this->baseUrl('auth'); ?>" class="button">Cancel</a> <input name="submit" id="submit" type="submit" class="button" value="OK">
            </form>
        </div>
    </section>
</div>
</body>