
                    <div class="cellContainer">
                        <ul class="score">
                            <li class="ball2"><a href="edit-score.html"><?php echo isset($this->throw2) ? $this->throw2['value'] : null;?></a></li>
                            <li class="ball1"><a href="edit-score.html"><?php echo isset($this->throw1) ? $this->throw1['value'] : null;?></a></li>
                            <li class="frameScore clear"><a href="edit-score.html"><?php echo @$this->total ?: '0';?></a></li>
                        </ul>
                    </div>