
            <tr>
                <td class="name">
                    <div class="cellContainer">
                        <div class="photo">
                           <?php echo $this->gravatar(
                               $this->user['email'], 
                               array('width'=> '100', 'height' => '100', 'alt' => $this->user['_id'])
                           );?>
                        </div>
                        <?php echo substr($this->user['_id'], 0 , 6)?>
                        <a href="stats.html" class="profile">Profile</a>
                    </div>
                </td>
                <td>
                <?php echo $this->frame($this->game['frames'][1]);?>
                </td>
                <td>
                <?php echo $this->frame($this->game['frames'][2]);?>
                </td>
                <td>
                <?php echo $this->frame($this->game['frames'][3]);?>
                </td>
                <td>
                <?php echo $this->frame($this->game['frames'][4]);?>
                </td>
            </tr>
            <tr class="divider">
                <td colspan="5"></td>
            </tr>