
            <tr>
                <td class="name">
                    <div class="cellContainer">
                        <div class="photo">
                           <?php echo $this->gravatar(
                               $this->user['email'], 
                               array('width'=> '100', 'height' => '100', 'alt' => $this->user['_id'])
                           );?>
                        </div>
                        <?php echo substr($this->user['_id'], 0 , 7)?>
                        <a href="<?php echo $this->baseUrl('player/stats')?>" class="profile">Profile</a>
                    </div>
                </td>
                <td>
                <?php echo $this->frame(1,$this->game['frames']);?>
                </td>
                <td>
                <?php echo $this->frame(2,$this->game['frames']);?>
                </td>
                <td>
                <?php echo $this->frame(3,$this->game['frames']);?>
                </td>
                <td>
                <?php echo $this->frame(4,$this->game['frames']);?>
                </td>
            </tr>
            <tr class="divider">
                <td colspan="5"></td>
            </tr>