<!DOCTYPE html>
 <html>
 <head>
     <meta charset="utf-8">
     <?php echo $this->headTitle();?>
    <?php
    $this->headLink()->appendStylesheet('/css/style.css');
    $this->headLink()->appendStylesheet('/sencha-touch/resources/css/sencha-touch.css');
    $this->headScript()->prependFile('/sencha-touch/sencha-touch-all.js');
    ?>
    <?php echo $this->headLink();?>

    <?php echo $this->headStyle();?>

    <?php echo $this->headScript();?>
 </head>
 <body><?php echo $this->layout()->content; ?></body>
 </html>
