<?php $this->headLink()->prependStylesheet('/css/style.css')->appendStylesheet('/css/pc.css');
$this->headScript()
    ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js')
    ->appendFile('/js/libs/modernizr-2.0.6.min.js')
    ->appendFile('/js/backbone.js')
    ->appendScript("window.jQuery || document.write('<script src=\"/js/libs/jquery-1.7.1.min.js\"><\/script>')");

?>
<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

	<title></title>
	<meta name="description" content="">
	<meta name="author" content="">

	<meta name="viewport" content="width=device-width,initial-scale=1">

<?php echo $this->headLink(), PHP_EOL, 
           $this->headScript(),PHP_EOL;
?>
</head>
<body>

<div id="container">
	<header>

	</header>
	<div id="main" role="main">
<?php echo $this->layout()->content; ?>
	</div>
	<footer>

	</footer>
</div> <!--! end of #container -->

<script>window.jQuery || document.write('<script src="/js/libs/jquery-1.7.1.min.js"><\/script>')</script>

<!-- scripts concatenated and minified via ant build script-->
<script src="js/plugins.js"></script>
<script src="js/script.js"></script>
<!-- end scripts-->

</body>
</html>
 