            <tr class="divider">
                <td colspan="5"></td>
            </tr>
            <tr<?php echo $this->currentBowler ? ' id="currentBowler"' : null?>>
                <td class="name">
                    <div class="cellContainer">
                        <div class="photo">
                            <img src="<?php echo $this->user['image']; ?>" alt="<?php echo $this->user['username']; ?>" width="100" height="100">
                        </div>
                        <?php echo $this->user['username']; ?>
                        <a href="stats.html" class="profile">Profile</a>
                    </div>
                </td>
                <td>
                    <a href="/game/score-frame/frame/5">
                        <div class="cellContainer">
                            <ul class="score">
                                <li class="ball2"><?php echo @$this->game['frames'][5]['throw2']?:'-';?></li>
                                <li class="ball1"><?php echo @$this->game['frames'][5]['throw1']?:null;?></li><br>
                                <li class="frameScore clear"><?php echo @$this->game['frames'][5]['total']?:0;?></li>
                            </ul>    
                        </div>
                    </a>
                </td>
                <td>
                    <a href="/game/score-frame/frame/6">
                        <div class="cellContainer">
                            <ul class="score">
                                <li class="ball2"><?php echo @$this->game['frames'][6]['throw2']?:'-';?></li>
                                <li class="ball1"><?php echo @$this->game['frames'][6]['throw1']?:null;?></li><br>
                                <li class="frameScore clear"><?php echo @$this->game['frames'][6]['total']?:0;?></li>
                            </ul>    
                        </div>
                    </a>
                </td>
                <td>
                    <a href="/game/score-frame/frame/7">
                        <div class="cellContainer">
                            <ul class="score">
                                <li class="ball2"><?php echo @$this->game['frames'][7]['throw2']?:'-';?></li>
                                <li class="ball1"><?php echo @$this->game['frames'][7]['throw1']?:null;?></li><br>
                                <li class="frameScore clear"><?php echo @$this->game['frames'][7]['total']?:0;?></li>
                            </ul>    
                        </div>
                    </a>
                </td>
                <td>
                    <a href="/game/score-frame/frame/8">
                        <div class="cellContainer">
                            <ul class="score">
                                <li class="ball2"><?php echo @$this->game['frames'][8]['throw2']?:'-';?></li>
                                <li class="ball1"><?php echo @$this->game['frames'][8]['throw1']?:null;?></li><br>
                                <li class="frameScore clear"><?php echo @$this->game['frames'][8]['total']?:0;?></li>
                            </ul>    
                        </div>
                    </a>
                </td>
            </tr>