            <tr class="divider">
                <td colspan="5"></td>
            </tr>
            <tr<?php echo $this->currentBowler ? ' id="currentBowler"' : null?>>
                <td class="name">
                    <div class="cellContainer">
                        <div class="photo">
                            <img src="<?php echo $this->user['image']; ?>" alt="<?php echo $this->user['username']; ?>" width="100" height="100">
                        </div>
                        <?php echo $this->user['username']; ?>
                        <a href="stats.html" class="profile">Profile</a>
                    </div>
                </td>
                <td>
                    <a href="/game/score-frame/frame/1">
                        <div class="cellContainer">
                            <ul class="score">
                                <li class="ball2"><?php echo @$this->game['frames'][1]['throw2']?:'-';?></li>
                                <li class="ball1"><?php echo @$this->game['frames'][1]['throw1']?:null;?></li><br>
                                <li class="frameScore clear"><?php echo @$this->game['frames'][1]['total']?:0;?></li>
                            </ul>
                        </div>
                    </a>
                </td>
                <td>
                    <a href="/game/score-frame/frame/2">
                        <div class="cellContainer">
                            <ul class="score">
                                <li class="ball2"><?php echo @$this->game['frames'][2]['throw2']?:'-';?></li>
                                <li class="ball1"><?php echo @$this->game['frames'][2]['throw1']?:null;?></li><br>
                                <li class="frameScore clear"><?php echo @$this->game['frames'][2]['total']?:0;?></li>
                            </ul>    
                        </div>
                    </a>
                </td>
                <td>
                    <a href="/game/score-frame/frame/3">
                        <div class="cellContainer">
                            <ul class="score">
                                <li class="ball2"><?php echo @$this->game['frames'][3]['throw2']?:'-';?></li>
                                <li class="ball1"><?php echo @$this->game['frames'][3]['throw1']?:null;?></li><br>
                                <li class="frameScore clear"><?php echo @$this->game['frames'][3]['total']?:0;?></li>
                            </ul>    
                        </div>
                    </a>
                </td>
                <td>
                    <a href="/game/score-frame/frame/4">
                        <div class="cellContainer">
                            <ul class="score">
                                <li class="ball2"><?php echo @$this->game['frames'][4]['throw2']?:'-';?></li>
                                <li class="ball1"><?php echo @$this->game['frames'][4]['throw1']?:null;?></li><br>
                                <li class="frameScore clear"><?php echo @$this->game['frames'][4]['total']?:0;?></li>
                            </ul>    
                        </div>
                    </a>
                </td>
            </tr>