            <tr class="divider">
                <td colspan="5"></td>
            </tr>            <tr<?php echo $this->currentBowler ? ' id="currentBowler"' : null?>>
                <td class="name">
                    <div class="cellContainer">
                        <div class="photo">
                            <img src="<?php echo $this->user['image']; ?>" alt="<?php echo $this->user['username']; ?>" width="100" height="100">
                        </div>
                        <?php echo $this->user['username']; ?>
                        <a href="stats.html" class="profile">Profile</a>
                    </div>
                </td>
                <td>
                    <a href="/game/score-frame/frame/9">
                        <div class="cellContainer">
                            <ul class="score">
                                <li class="ball2"><?php echo @$this->game['frames'][9]['throw2']?:'-';?></li>
                                <li class="ball1"><?php echo @$this->game['frames'][9]['throw1']?:null;?></li><br>
                                <li class="frameScore clear"><?php echo @$this->game['frames'][9]['total']?:'0';?></li>
                            </ul>
                        </div>
                    </a>
                </td>
                <td>
                    <a href="/game/score-frame/frame/10">
                        <div class="cellContainer">
                            <ul class="score">
                                <li class="ball3"><?php echo @$this->game['frames'][10]['throw3']?:'-';?></li>
                                <li class="ball2"><?php echo @$this->game['frames'][10]['throw2']?:'-';?></li>
                                <li class="ball1"><?php echo @$this->game['frames'][10]['throw1']?:null;?></li><br>
                                <li class="frameScore clear"><?php echo @$this->game['frames'][10]['total']?:'0';?></li>
                            </ul>
                        </div>
                    </a>
                </td>
                <td class="total"><?php echo @$this->game['total']?:null;?></td>
                <td>
                    <ul class="finishOptions">
                        <li><a href="stats.html" class="button">Stats</a></li>
                        <li><a href="share.html" class="button">Share</a></li>
                        <li><a href="view-game.html" class="button">View game</a></li>
                    </ul>
                </td>
            </tr>